/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.insy.bank_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static com.insy.bank_system.Constants.*;

/**
 *
 * @author CTM
 */
public class AccountantPage extends javax.swing.JFrame {

    /**
     * Creates new form AccountantPage
     */
    public AccountantPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Logoutbtn = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editname = new javax.swing.JTextField();
        editdate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        editnation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editbalance = new javax.swing.JTextField();
        Editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        accountno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sexbox = new javax.swing.JComboBox<>();
        statfield = new javax.swing.JLabel();
        activebtn = new javax.swing.JButton();
        blockbtn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        hisbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sexfield = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nationfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accnofield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        createbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        phone_no = new javax.swing.JTextField();

        jTextField5.setText("jTextField5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(738, 446));
        setMinimumSize(new java.awt.Dimension(738, 446));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("ADWA BANK ");

        Logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        searchfield.setDragEnabled(true);

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logoutbtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchbtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Logoutbtn)))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Name :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Birth Date :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Sex :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Nationality :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Account Number :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Balance :");

        Editbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Editbtn.setForeground(new java.awt.Color(51, 51, 255));
        Editbtn.setText("EDIT");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 0, 0));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Phone number :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Status :");

        sexbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        statfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statfield.setText("active");

        activebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        activebtn.setForeground(new java.awt.Color(0, 0, 204));
        activebtn.setText("ACTIVATE");
        activebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activebtnActionPerformed(evt);
            }
        });

        blockbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blockbtn.setForeground(new java.awt.Color(255, 0, 0));
        blockbtn.setText("BLOCK");
        blockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockbtnActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear_btn.setText("CLEAR");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        hisbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hisbtn.setText("History");
        hisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel23Layout = new javax.swing.GroupLayout(jpanel23);
        jpanel23.setLayout(jpanel23Layout);
        jpanel23Layout.setHorizontalGroup(
            jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel23Layout.createSequentialGroup()
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanel23Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(Editbtn)
                        .addGap(36, 36, 36)
                        .addComponent(deletebtn))
                    .addGroup(jpanel23Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel23Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clear_btn))
                            .addGroup(jpanel23Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(editname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanel23Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpanel23Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel15)))
                                .addGap(18, 18, 18)
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editnation, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(editbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(phonefield)))
                            .addGroup(jpanel23Layout.createSequentialGroup()
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statfield, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(activebtn)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel23Layout.createSequentialGroup()
                                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpanel23Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel23Layout.createSequentialGroup()
                                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel23Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(hisbtn)))
                                        .addGap(76, 76, 76)))
                                .addGap(4, 4, 4)
                                .addComponent(blockbtn)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jpanel23Layout.setVerticalGroup(
            jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel23Layout.createSequentialGroup()
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel23Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(accountno)
                            .addComponent(clear_btn)
                            .addComponent(hisbtn))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(editname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(editbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(editnation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editbtn)
                    .addComponent(deletebtn)
                    .addComponent(jLabel17)
                    .addComponent(statfield)
                    .addComponent(activebtn)
                    .addComponent(blockbtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", jpanel23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Birth day :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Sex :");

        sexfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nationality :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Account no :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Password :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Deposite Amount :");

        createbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createbutton.setText("Create");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Phone Number :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createbutton)
                .addGap(56, 56, 56)
                .addComponent(clearbutton)
                .addGap(131, 131, 131))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datefield, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(namefield))
                        .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(phone_no, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sexfield, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE))
                    .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sexfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createbutton)
                    .addComponent(clearbutton))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("create account", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        // TODO add your handling code here:
        String name = namefield.getText();
        String date = datefield.getText();
        String sex = sexfield.getSelectedItem().toString();
        String national = nationfield.getText();
        String accno = accnofield.getText();
        String pass = new String(passfield.getPassword());
        String amount = amountfield.getText();
        String phone = phone_no.getText();
        if (name.isEmpty() || date.isEmpty() || national.isEmpty() || accno.isEmpty() || pass.isEmpty() || amount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill The Form");
        }

        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement ps = con.prepareStatement(
                    "insert into user"
                    + "(name,birth_date,phone_number,"
                    + "sex,nationality,account,"
                    + "password,balance,status)values(?,?,?,?,?,?,?,?,?)");

            ps.setString(1, name);
            ps.setString(2, date);
            ps.setString(3, phone);
            ps.setString(4, sex);
            ps.setString(5, national);
            ps.setString(6, accno);
            ps.setString(7, pass);
            ps.setString(8, amount);
            ps.setString(9, "Active");
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Created Sucsessfully", date, HEIGHT);

            namefield.setText("");
            datefield.setText("");
            phone_no.setText("");
            nationfield.setText("");
            accnofield.setText("");
            passfield.setText("");
            amountfield.setText("");
            namefield.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        namefield.setText("");
        datefield.setText("");
        phone_no.setText("");
        nationfield.setText("");
        accnofield.setText("");
        passfield.setText("");
        amountfield.setText("");
        namefield.requestFocus();

    }//GEN-LAST:event_clearbuttonActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String search = searchfield.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Account Number");
        }
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            
            PreparedStatement statement = con.prepareStatement("SELECT * FROM user WHERE account = ?");
            statement.setString(1, search);
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                String name = result.getString("name");
                editname.setText(name);
                String birthdate = result.getString("birth_date");
                editdate.setText(birthdate);
                String phone = result.getString("phone_number");
                phonefield.setText(phone);
                String sex = result.getString("sex");
                if (sex.equals("Male")) {
                    sexbox.setSelectedIndex(0);
                } else if (sex.equals("Female")) {
                    sexbox.setSelectedIndex(1);
                }
                String nation = result.getString("nationality");
                editnation.setText(nation);
                String acc = result.getString("account");
                accountno.setText(acc);
                String bal = result.getString("balance");
                editbalance.setText(bal);
                String stat = result.getString("status");
                statfield.setText(stat);

            }

            searchfield.setText("");
            searchfield.requestFocus();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = 0;
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement statement = con.prepareStatement("SELECT * FROM user WHERE account = ?");
            statement.setString(1, accountno.getText());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                int index = Integer.parseInt(result.getString("id"));
                id = index;
            }
            PreparedStatement stat = con.prepareStatement("DELETE FROM user WHERE id = ?");
            stat.setInt(1, id);
            stat.executeUpdate();

            accountno.setText("");
            editname.setText("");
            phonefield.setText("");
            editdate.setText("");
            editbalance.setText("");
            editnation.setText("");
            searchfield.requestFocus();
            
            JOptionPane.showMessageDialog(this, "Account Has DELETED");
            

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_deletebtnActionPerformed


    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;
            if (editname.getText().isEmpty() || editdate.getText().isEmpty() || phonefield.getText().isEmpty() || editnation.getText().isEmpty() || editbalance.getText().isEmpty() || accountno.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill The Form");
            } else {
                Connection con = DriverManager.getConnection(url, username, password);
                Statement stat = con.createStatement();
                PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
                statement.setString(1, editname.getText());
                statement.setString(2, editdate.getText());
                statement.setString(3, phonefield.getText());
                statement.setString(4, sexbox.getSelectedItem().toString());
                statement.setString(5, editnation.getText());
                statement.setString(6, editbalance.getText());
                statement.setString(7, statfield.getText());
                statement.setString(8, accountno.getText());
                statement.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Account Has be Updated");
                
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EditbtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // logout page
        dispose();
        LoginPage li = new LoginPage();
        li.setVisible(true);

    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void activebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activebtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
            statement.setString(1, editname.getText());
            statement.setString(2, editdate.getText());
            statement.setString(3, phonefield.getText());
            statement.setString(4, sexbox.getSelectedItem().toString());
            statement.setString(5, editnation.getText());
            statement.setString(6, editbalance.getText());
            statement.setString(7, "Active");
            statement.setString(8, accountno.getText());
            statement.executeUpdate();

            statfield.setText("Active");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_activebtnActionPerformed

    private void blockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
            statement.setString(1, editname.getText());
            statement.setString(2, editdate.getText());
            statement.setString(3, phonefield.getText());
            statement.setString(4, sexbox.getSelectedItem().toString());
            statement.setString(5, editnation.getText());
            statement.setString(6, editbalance.getText());
            statement.setString(7, "Block");
            statement.setString(8, accountno.getText());
            statement.executeUpdate();

            statfield.setText("Block");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_blockbtnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
            accountno.setText("");
            editname.setText("");
            phonefield.setText("");
            editdate.setText("");
            editbalance.setText("");
            editnation.setText("");
            searchfield.requestFocus();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void hisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hisbtnActionPerformed
        // TODO add your handling code here:
        Transactionpage tp = new Transactionpage(accountno.getText());
        tp.setVisible(true);
        
    }//GEN-LAST:event_hisbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountantPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccountantPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editbtn;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JTextField accnofield;
    private javax.swing.JLabel accountno;
    private javax.swing.JButton activebtn;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton blockbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton createbutton;
    private javax.swing.JTextField datefield;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField editbalance;
    private javax.swing.JTextField editdate;
    private javax.swing.JTextField editname;
    private javax.swing.JTextField editnation;
    private javax.swing.JButton hisbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel jpanel23;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField nationfield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JComboBox<String> sexbox;
    private javax.swing.JComboBox<String> sexfield;
    private javax.swing.JLabel statfield;
    // End of variables declaration//GEN-END:variables
}
