/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.insy.bank_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static com.insy.bank_system.Constants.*;


/**
 *
 * @author CTM
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Logoutbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editname = new javax.swing.JTextField();
        editdate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        editnation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editbalance = new javax.swing.JTextField();
        Editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        accountno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sexbox = new javax.swing.JComboBox<>();
        statfield = new javax.swing.JLabel();
        activebtn = new javax.swing.JButton();
        blockbtn = new javax.swing.JButton();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        user_clearbtn = new javax.swing.JButton();
        historybtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sexfield = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nationfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accnofield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        createbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        phone_no = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jpanel24 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        manager_editname1 = new javax.swing.JTextField();
        manager_editdate1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Editbtn1 = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();
        id_no1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        manager_phonefield1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        manager_sexbox1 = new javax.swing.JComboBox<>();
        manager_statfield1 = new javax.swing.JLabel();
        activebtn1 = new javax.swing.JButton();
        blockbtn1 = new javax.swing.JButton();
        manager_searchfield1 = new javax.swing.JTextField();
        searchbtn1 = new javax.swing.JButton();
        manager_editnation1 = new javax.swing.JTextField();
        manager_clearbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        manager_namefield1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        manager_datefield1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        manager_sexfield1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        manager_nationfield1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        manager_idnofield1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        create_manager_btn = new javax.swing.JButton();
        clearbutton1 = new javax.swing.JButton();
        manager_passfield1 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        manager_phone_no1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("WELCOME TO ADWA BANK");

        Logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(Logoutbtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logoutbtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Name :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Birth Date :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Sex :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Nationality :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Account Number :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Balance :");

        Editbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Editbtn.setForeground(new java.awt.Color(51, 51, 255));
        Editbtn.setText("EDIT");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 0, 0));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Phone number :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Status :");

        sexbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        statfield.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statfield.setText("active");

        activebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        activebtn.setForeground(new java.awt.Color(0, 0, 204));
        activebtn.setText("ACTIVATE");
        activebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activebtnActionPerformed(evt);
            }
        });

        blockbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blockbtn.setForeground(new java.awt.Color(255, 0, 0));
        blockbtn.setText("BLOCK");
        blockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockbtnActionPerformed(evt);
            }
        });

        searchfield.setDragEnabled(true);

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        user_clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user_clearbtn.setText("CLEAR");
        user_clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_clearbtnActionPerformed(evt);
            }
        });

        historybtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        historybtn.setText("HISTORY");
        historybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel23Layout = new javax.swing.GroupLayout(jpanel23);
        jpanel23.setLayout(jpanel23Layout);
        jpanel23Layout.setHorizontalGroup(
            jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel23Layout.createSequentialGroup()
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel23Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel23Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(editname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanel23Layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpanel23Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel15)))
                                .addGap(18, 18, 18)
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editnation, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(editbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(phonefield)))
                            .addGroup(jpanel23Layout.createSequentialGroup()
                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statfield, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(activebtn)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel23Layout.createSequentialGroup()
                                        .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpanel23Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel23Layout.createSequentialGroup()
                                                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(editdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(historybtn, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(76, 76, 76))
                                    .addGroup(jpanel23Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(accountno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addComponent(blockbtn))))
                    .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel23Layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(searchbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user_clearbtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel23Layout.createSequentialGroup()
                            .addGap(467, 467, 467)
                            .addComponent(Editbtn)
                            .addGap(36, 36, 36)
                            .addComponent(deletebtn))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jpanel23Layout.setVerticalGroup(
            jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel23Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn)
                    .addComponent(user_clearbtn)
                    .addComponent(historybtn))
                .addGap(18, 18, 18)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(accountno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(phonefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(editbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(editnation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jpanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editbtn)
                    .addComponent(deletebtn)
                    .addComponent(jLabel17)
                    .addComponent(statfield)
                    .addComponent(activebtn)
                    .addComponent(blockbtn))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users Account Manager", jpanel23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Birth day :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Sex :");

        sexfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nationality :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Account no :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Password :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Deposite Amount :");

        createbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createbutton.setText("Create");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Phone Number :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createbutton)
                .addGap(56, 56, 56)
                .addComponent(clearbutton)
                .addGap(131, 131, 131))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datefield, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(namefield))
                        .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(phone_no, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sexfield, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE))
                    .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sexfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(accnofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(amountfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createbutton)
                    .addComponent(clearbutton))
                .addGap(57, 57, 57))
        );

        jTabbedPane1.addTab("Create User Account", jPanel3);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Name :");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Birth Date :");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Sex :");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Nationality :");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("ID Number :");

        Editbtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Editbtn1.setForeground(new java.awt.Color(51, 51, 255));
        Editbtn1.setText("EDIT");
        Editbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editbtn1ActionPerformed(evt);
            }
        });

        deletebtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletebtn1.setForeground(new java.awt.Color(255, 0, 0));
        deletebtn1.setText("DELETE");
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Phone number :");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Status :");

        manager_sexbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        manager_statfield1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manager_statfield1.setText("active");

        activebtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        activebtn1.setForeground(new java.awt.Color(0, 0, 204));
        activebtn1.setText("ACTIVATE");
        activebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activebtn1ActionPerformed(evt);
            }
        });

        blockbtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blockbtn1.setForeground(new java.awt.Color(255, 0, 0));
        blockbtn1.setText("BLOCK");
        blockbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockbtn1ActionPerformed(evt);
            }
        });

        manager_searchfield1.setDragEnabled(true);

        searchbtn1.setText("Search");
        searchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtn1ActionPerformed(evt);
            }
        });

        manager_clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manager_clearbtn.setText("CLEAR");
        manager_clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manager_clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel24Layout = new javax.swing.GroupLayout(jpanel24);
        jpanel24.setLayout(jpanel24Layout);
        jpanel24Layout.setHorizontalGroup(
            jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel24Layout.createSequentialGroup()
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel24Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(Editbtn1)
                        .addGap(36, 36, 36)
                        .addComponent(deletebtn1))
                    .addGroup(jpanel24Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpanel24Layout.createSequentialGroup()
                                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel24Layout.createSequentialGroup()
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(manager_statfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(activebtn1)
                                        .addGap(25, 25, 25))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel24Layout.createSequentialGroup()
                                        .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpanel24Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(manager_sexbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel24Layout.createSequentialGroup()
                                                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(manager_editdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(76, 76, 76))
                                    .addGroup(jpanel24Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(id_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpanel24Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(blockbtn1)
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel24Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))))
                            .addGroup(jpanel24Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(manager_editname1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel31)
                                .addGap(26, 26, 26)
                                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manager_editnation1)
                                    .addComponent(manager_phonefield1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jpanel24Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(manager_searchfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchbtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manager_clearbtn)
                .addGap(76, 76, 76))
        );
        jpanel24Layout.setVerticalGroup(
            jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel24Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manager_searchfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn1)
                    .addComponent(manager_clearbtn))
                .addGap(18, 18, 18)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(id_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(manager_editname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(manager_phonefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(manager_editdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(manager_editnation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(manager_sexbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jpanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editbtn1)
                    .addComponent(deletebtn1)
                    .addComponent(jLabel32)
                    .addComponent(manager_statfield1)
                    .addComponent(activebtn1)
                    .addComponent(blockbtn1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Manager Account Manager", jPanel2);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Name :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Birth day :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Sex :");

        manager_sexfield1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Nationality :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("ID no :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Password :");

        create_manager_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        create_manager_btn.setText("Create");
        create_manager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_manager_btnActionPerformed(evt);
            }
        });

        clearbutton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton1.setText("Clear");
        clearbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutton1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Phone Number :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(create_manager_btn)
                .addGap(56, 56, 56)
                .addComponent(clearbutton1)
                .addGap(131, 131, 131))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jLabel19))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manager_datefield1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(manager_namefield1))
                        .addComponent(manager_idnofield1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manager_passfield1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manager_nationfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manager_phone_no1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(manager_sexfield1, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(manager_namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(manager_phone_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manager_sexfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manager_nationfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manager_datefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manager_idnofield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manager_passfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_manager_btn)
                    .addComponent(clearbutton1))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Manager Account Creator", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // logout page
        dispose();
        LoginPage li = new LoginPage();
        li.setVisible(true);
    }//GEN-LAST:event_LogoutbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        /*
        user search button
         */
        String searchText = searchfield.getText();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Account Number");
        }
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement statement = con.prepareStatement("SELECT * FROM user WHERE account = ?");
            statement.setString(1, searchText);
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                String name = result.getString("name");
                editname.setText(name);
                String birthdate = result.getString("birth_date");
                editdate.setText(birthdate);
                String phone = result.getString("phone_number");
                phonefield.setText(phone);
                String sex = result.getString("sex");
                if (sex.equals("Male")) {
                    sexbox.setSelectedIndex(0);
                } else if (sex.equals("Female")) {
                    sexbox.setSelectedIndex(1);
                }
                String nation = result.getString("nationality");
                editnation.setText(nation);
                String acc = result.getString("account");
                accountno.setText(searchText);
                String bal = result.getString("balance");
                editbalance.setText(bal);
                String stat = result.getString("status");
                statfield.setText(stat);

            }

            searchfield.setText("");
            searchfield.requestFocus();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed

        /*
        user edit button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;
            if (editname.getText().isEmpty() || editdate.getText().isEmpty() || phonefield.getText().isEmpty() || editnation.getText().isEmpty() || editbalance.getText().isEmpty() || accountno.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill The Form");
            } else {
                Connection con = DriverManager.getConnection(url, username, password);
                Statement stat = con.createStatement();
                PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
                statement.setString(1, editname.getText());
                statement.setString(2, editdate.getText());
                statement.setString(3, phonefield.getText());
                statement.setString(4, sexbox.getSelectedItem().toString());
                statement.setString(5, editnation.getText());
                statement.setString(6, editbalance.getText());
                statement.setString(7, statfield.getText());
                statement.setString(8, accountno.getText());
                statement.executeUpdate();

                JOptionPane.showMessageDialog(this, "Account Has be Updated");

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EditbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed

        /*
        user delete button
         */
        try {
            int id = 0;
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement statement = con.prepareStatement("SELECT * FROM user WHERE account = ?");
            statement.setString(1, accountno.getText());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                int index = Integer.parseInt(result.getString("id"));
                id = index;
            }
            PreparedStatement stat = con.prepareStatement("DELETE FROM user WHERE id = ?");
            stat.setInt(1, id);
            stat.executeUpdate();

            accountno.setText("");
            editname.setText("");
            phonefield.setText("");
            editdate.setText("");
            editbalance.setText("");
            editnation.setText("");
            searchfield.requestFocus();

            JOptionPane.showMessageDialog(this, "Account Has DELETED");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void activebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activebtnActionPerformed

        /*
        user activation button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
            statement.setString(1, editname.getText());
            statement.setString(2, editdate.getText());
            statement.setString(3, phonefield.getText());
            statement.setString(4, sexbox.getSelectedItem().toString());
            statement.setString(5, editnation.getText());
            statement.setString(6, editbalance.getText());
            statement.setString(7, "Active");
            statement.setString(8, accountno.getText());
            statement.executeUpdate();

            statfield.setText("Active");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_activebtnActionPerformed

    private void blockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockbtnActionPerformed

        /*
        user block button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE user SET name = ? , birth_date = ? , phone_number = ? , sex = ? , nationality = ? , balance = ? , status = ? WHERE account = ?");
            statement.setString(1, editname.getText());
            statement.setString(2, editdate.getText());
            statement.setString(3, phonefield.getText());
            statement.setString(4, sexbox.getSelectedItem().toString());
            statement.setString(5, editnation.getText());
            statement.setString(6, editbalance.getText());
            statement.setString(7, "Block");
            statement.setString(8, accountno.getText());
            statement.executeUpdate();

            statfield.setText("Block");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_blockbtnActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        /*
        user create button
         */
        String name = namefield.getText();
        String date = datefield.getText();
        String sex = sexfield.getSelectedItem().toString();
        String national = nationfield.getText();
        String accno = accnofield.getText();
        String pass = new String(passfield.getPassword());
        String amount = amountfield.getText();
        String phone = phone_no.getText();
        if (name.isEmpty() || phone.isEmpty() || date.isEmpty() || national.isEmpty() || accno.isEmpty() || pass.isEmpty() || amount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill The Form");
        } else {
            try {
                Class.forName(JDBC_DRIVER);
                String url = CONNECTION_URL;
                String username = DB_USERNAME;
                String password = DB_PASSWORD;

                Connection con = DriverManager.getConnection(url, username, password);
                PreparedStatement ps = con.prepareStatement(
                        "insert into user"
                        + "(name,birth_date,phone_number,"
                        + "sex,nationality,account,"
                        + "password,balance,status)values(?,?,?,?,?,?,?,?,?)");

                ps.setString(1, name);
                ps.setString(2, date);
                ps.setString(3, phone);
                ps.setString(4, sex);
                ps.setString(5, national);
                ps.setString(6, accno);
                ps.setString(7, pass);
                ps.setString(8, amount);
                ps.setString(9, "Active");
                ps.executeUpdate();

             
                JOptionPane.showMessageDialog(this, "Created Sucsessfully", date, HEIGHT);

                namefield.setText("");
                datefield.setText("");
                phone_no.setText("");
                nationfield.setText("");
                accnofield.setText("");
                passfield.setText("");
                amountfield.setText("");
                namefield.requestFocus();

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_createbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        /*
        user clear button
         */
        namefield.setText("");
        datefield.setText("");
        phonefield.setText("");
        nationfield.setText("");
        accnofield.setText("");
        passfield.setText("");
        amountfield.setText("");
        namefield.requestFocus();

    }//GEN-LAST:event_clearbuttonActionPerformed

    private void create_manager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_manager_btnActionPerformed

        /*
        manager create button
         */
        String name = manager_namefield1.getText();
        String date = manager_datefield1.getText();
        String sex = manager_sexfield1.getSelectedItem().toString();
        String national = manager_nationfield1.getText();
        String id_no = manager_idnofield1.getText();
        String pass = new String(manager_passfield1.getPassword());
        String phone = manager_phone_no1.getText();
        if (name.isEmpty() || date.isEmpty() || phone.isEmpty() || national.isEmpty() || id_no.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill The Form");
        } else {
            try {
                Class.forName(JDBC_DRIVER);
                String url = CONNECTION_URL;
                String username = DB_USERNAME;
                String password = DB_PASSWORD;

                Connection con = DriverManager.getConnection(url, username, password);
                PreparedStatement ps = con.prepareStatement(
                        "insert into manager"
                        + "(name,date,phone,"
                        + "sex,national,id_no,"
                        + "pass,status)values(?,?,?,?,?,?,?,?)");

                ps.setString(1, name);
                ps.setString(2, date);
                ps.setString(3, phone);
                ps.setString(4, sex);
                ps.setString(5, national);
                ps.setString(6, id_no);
                ps.setString(7, pass);
                ps.setString(8, "Active");
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Created Sucsessfully", date, HEIGHT);

                manager_namefield1.setText("");
                manager_datefield1.setText("");
                manager_idnofield1.setText("");
                manager_passfield1.setText("");
                manager_phone_no1.setText("");
                manager_nationfield1.setText("");

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_create_manager_btnActionPerformed

    private void clearbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutton1ActionPerformed

        /*
        manager clear button
         */
        manager_namefield1.setText("");
        manager_datefield1.setText("");
        manager_idnofield1.setText("");
        manager_passfield1.setText("");
        manager_phone_no1.setText("");
        manager_nationfield1.setText("");
    }//GEN-LAST:event_clearbutton1ActionPerformed

    private void Editbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editbtn1ActionPerformed

        /*
        manager edit button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;
            if (manager_editname1.getText().isEmpty() || manager_editdate1.getText().isEmpty() || manager_phonefield1.getText().isEmpty() || manager_editnation1.getText().isEmpty() || id_no1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill The Form");
            } else {
                Connection con = DriverManager.getConnection(url, username, password);
                Statement stat = con.createStatement();
                PreparedStatement statement = con.prepareStatement("UPDATE manager SET name = ? , date = ? , phone = ? , sex = ? , national = ? , status = ? WHERE id_no = ?");
                statement.setString(1, manager_editname1.getText());
                statement.setString(2, manager_editdate1.getText());
                statement.setString(3, manager_phonefield1.getText());
                statement.setString(4, manager_sexbox1.getSelectedItem().toString());
                statement.setString(5, manager_editnation1.getText());
                statement.setString(6, manager_statfield1.getText());
                statement.setString(7, id_no1.getText());
                statement.executeUpdate();

                JOptionPane.showMessageDialog(this, "Account Has be Updated");

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Editbtn1ActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed

        /*
        manager delete button
         */
        try {
            int id = 0;
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement statement = con.prepareStatement("SELECT * FROM manager WHERE id_no = ?");
            statement.setString(1, id_no1.getText());
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                int index = Integer.parseInt(result.getString("id"));
                id = index;
            }
            PreparedStatement stat = con.prepareStatement("DELETE FROM manager WHERE id = ?");
            stat.setInt(1, id);
            stat.executeUpdate();

            manager_editname1.setText("");
            manager_searchfield1.setText("");
            id_no1.setText("");
            manager_editdate1.setText("");
            manager_phonefield1.setText("");
            manager_editnation1.setText("");

            JOptionPane.showMessageDialog(this, "Account Has DELETED");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebtn1ActionPerformed

    private void activebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activebtn1ActionPerformed

        /*
        manager activation button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE manager SET name = ? , date = ? , phone = ? , sex = ? , national = ? , status = ? WHERE id_no = ?");
            statement.setString(1, manager_editname1.getText());
            statement.setString(2, manager_editdate1.getText());
            statement.setString(3, manager_phonefield1.getText());
            statement.setString(4, manager_sexbox1.getSelectedItem().toString());
            statement.setString(5, manager_editnation1.getText());
            statement.setString(6, "Active");
            statement.setString(7, id_no1.getText());
            statement.executeUpdate();

            manager_statfield1.setText("Active");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_activebtn1ActionPerformed

    private void blockbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockbtn1ActionPerformed

        /*
        user block button
         */
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("UPDATE manager SET name = ? , date = ? , phone = ? , sex = ? , national = ? , status = ? WHERE id_no = ?");
            statement.setString(1, manager_editname1.getText());
            statement.setString(2, manager_editdate1.getText());
            statement.setString(3, manager_phonefield1.getText());
            statement.setString(4, manager_sexbox1.getSelectedItem().toString());
            statement.setString(5, manager_editnation1.getText());
            statement.setString(6, "Block");
            statement.setString(7, id_no1.getText());
            statement.executeUpdate();

            manager_statfield1.setText("Block");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_blockbtn1ActionPerformed

    private void searchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtn1ActionPerformed

        /*
        manager search button
         */
        String search = manager_searchfield1.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter ID Number");
        } else {
            try {
                Class.forName(JDBC_DRIVER);
                String url = CONNECTION_URL;
                String username = DB_USERNAME;
                String password = DB_PASSWORD;

                Connection con = DriverManager.getConnection(url, username, password);
                PreparedStatement statement = con.prepareStatement("SELECT * FROM manager WHERE id_no = ?");
                statement.setString(1, search);
                ResultSet result = statement.executeQuery();
                
                    while (result.next()) {
                        
                        String name = result.getString("name");
                        manager_editname1.setText(name);
                        String birthdate = result.getString("date");
                        manager_editdate1.setText(birthdate);
                        String phone = result.getString("phone");
                        manager_phonefield1.setText(phone);
                        String sex = result.getString("sex");
                        if (sex.equals("Male")) {
                            manager_sexbox1.setSelectedIndex(0);
                        } else if (sex.equals("Female")) {
                            manager_sexbox1.setSelectedIndex(1);
                        }
                        String nation = result.getString("national");
                        manager_editnation1.setText(nation);
                        String acc = result.getString("id_no");
                        id_no1.setText(acc);
                        String stat = result.getString("status");
                        manager_statfield1.setText(stat);
                    }


                manager_searchfield1.setText("");
                manager_searchfield1.requestFocus();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_searchbtn1ActionPerformed

    private void manager_clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manager_clearbtnActionPerformed
        // TODO add your handling code here:
        manager_editname1.setText("");
        manager_searchfield1.setText("");
        id_no1.setText("");
        manager_editdate1.setText("");
        manager_phonefield1.setText("");
        manager_editnation1.setText("");
    }//GEN-LAST:event_manager_clearbtnActionPerformed

    private void user_clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_clearbtnActionPerformed
        // TODO add your handling code here:
            accountno.setText("");
            editname.setText("");
            phonefield.setText("");
            editdate.setText("");
            editbalance.setText("");
            editnation.setText("");
            searchfield.requestFocus();
    }//GEN-LAST:event_user_clearbtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        // TODO add your handling code here:
        Transactionpage tp = new Transactionpage(accountno.getText());
        tp.setVisible(true);
    }//GEN-LAST:event_historybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editbtn;
    private javax.swing.JButton Editbtn1;
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JTextField accnofield;
    private javax.swing.JLabel accountno;
    private javax.swing.JButton activebtn;
    private javax.swing.JButton activebtn1;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton blockbtn;
    private javax.swing.JButton blockbtn1;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton clearbutton1;
    private javax.swing.JButton create_manager_btn;
    private javax.swing.JButton createbutton;
    private javax.swing.JTextField datefield;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JTextField editbalance;
    private javax.swing.JTextField editdate;
    private javax.swing.JTextField editname;
    private javax.swing.JTextField editnation;
    private javax.swing.JButton historybtn;
    private javax.swing.JLabel id_no1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanel23;
    private javax.swing.JPanel jpanel24;
    private javax.swing.JButton manager_clearbtn;
    private javax.swing.JTextField manager_datefield1;
    private javax.swing.JTextField manager_editdate1;
    private javax.swing.JTextField manager_editname1;
    private javax.swing.JTextField manager_editnation1;
    private javax.swing.JTextField manager_idnofield1;
    private javax.swing.JTextField manager_namefield1;
    private javax.swing.JTextField manager_nationfield1;
    private javax.swing.JPasswordField manager_passfield1;
    private javax.swing.JTextField manager_phone_no1;
    private javax.swing.JTextField manager_phonefield1;
    private javax.swing.JTextField manager_searchfield1;
    private javax.swing.JComboBox<String> manager_sexbox1;
    private javax.swing.JComboBox<String> manager_sexfield1;
    private javax.swing.JLabel manager_statfield1;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField nationfield;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton searchbtn1;
    private javax.swing.JTextField searchfield;
    private javax.swing.JComboBox<String> sexbox;
    private javax.swing.JComboBox<String> sexfield;
    private javax.swing.JLabel statfield;
    private javax.swing.JButton user_clearbtn;
    // End of variables declaration//GEN-END:variables
}
