/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.insy.bank_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static com.insy.bank_system.Constants.*;

/**
 *
 * @author CTM
 */
public class Transactionpage extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public Transactionpage(String accnum) {
        initComponents();
        int count;

        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);

            //Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("SELECT * FROM transaction WHERE account_no = ?");
            statement.setString(1, accnum);
            ResultSet result = statement.executeQuery();
            ResultSetMetaData rd = result.getMetaData();
            count = rd.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) history_table.getModel();
            df.setRowCount(0);

            while (result.next()) {
                Vector v = new Vector();

                for (int a = 1; a <= count; a++) {
                    v.add(result.getString("id"));
                    v.add(result.getString("transaction_type"));
                    v.add(result.getString("amount"));
                    
                }

                df.addRow(v);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        history_table = new javax.swing.JTable();
        canclebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TRANSACTION");

        history_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Type", "Amount"
            }
        ));
        history_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                history_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(history_table);

        canclebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        canclebtn.setText("Cancel");
        canclebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canclebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(canclebtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(canclebtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void history_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_tableMouseClicked
        // TODO add your handling code here:
        String toacc, fromacc, t_amount, t_reason, ttype;
        
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);

            //Statement stat = con.createStatement();
            DefaultTableModel df = (DefaultTableModel) history_table.getModel();
            int selectedrow = history_table.getSelectedRow();
            int index = Integer.parseInt(df.getValueAt(selectedrow, 0).toString());
            
            PreparedStatement statement = con.prepareStatement("SELECT * FROM transaction WHERE id = ?");
            statement.setInt(1, index);
            ResultSet result_2 = statement.executeQuery();
            while (result_2.next()) {
                toacc = result_2.getString("to_acc");
                fromacc = result_2.getString("from_acc");
                t_amount = result_2.getString("amount");
                t_reason = result_2.getString("reason");
                ttype = result_2.getString("transaction_type");
                if (ttype.equals("Withdraw")) {
                    JOptionPane.showMessageDialog(this, DB_PASSWORD
                            + "Amount = " + t_amount + "\n"
                            + ttype);
                } else if (ttype.equals("Deposite")) {
                    JOptionPane.showMessageDialog(this, DB_PASSWORD
                            + "Amount = " + t_amount + "\n"
                            + "From = " + fromacc + "\n"
                            + "Reason = " + t_reason + "\n"
                            + ttype);
                } else if (ttype.equals("Transfer")) {
                    JOptionPane.showMessageDialog(this, DB_PASSWORD
                            + "Amount = " + t_amount + "\n"
                            + "To = " + toacc + "\n"
                            + "Reason = " + t_reason + "\n"
                            + ttype);
                }

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_history_tableMouseClicked

    private void canclebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canclebtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_canclebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canclebtn;
    private javax.swing.JTable history_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
