/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.insy.bank_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static com.insy.bank_system.Constants.*;

/**
 *
 * @author CTM
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    String passw = "";
    

    private void transaction_table(String accnum) {
        int count;

        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);

            //Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("SELECT * FROM transaction WHERE account_no = ?");
            statement.setString(1, accnum);
            ResultSet result = statement.executeQuery();
            ResultSetMetaData rd = result.getMetaData();
            count = rd.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) history_table.getModel();
            df.setRowCount(0);

            while (result.next()) {
                Vector v = new Vector();

                for (int a = 1; a <= count; a++) {
                    v.add(result.getString("id"));
                    v.add(result.getString("transaction_type"));
                    v.add(result.getString("amount"));
                    
                }

                df.addRow(v);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public UserPage(String accnum) throws SQLException {
        initComponents();
        accountfield.setText(accnum);
        transaction_table(accnum);
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);

            //Statement stat = con.createStatement();
            PreparedStatement statement = con.prepareStatement("SELECT * FROM user WHERE account = ?");
            statement.setString(1, accnum);
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                String name = result.getString("name");
                namefield.setText(name);
                String birthdate = result.getString("birth_date");
                datefield.setText(birthdate);
                String sex = result.getString("sex");
                sexfield.setText(sex);
                String nation = result.getString("nationality");
                nationfield.setText(nation);
                String phone = result.getString("phone_number");
                phone_no.setText(phone);
                String bal = result.getString("balance");
                balancefeild.setText(bal);
                balance2field.setText(bal);
                balance3field.setText(bal);
                String pass = result.getString("password");
                passw = pass;

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        notificationbtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        namefield = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accountfield = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        balancefeild = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        datefield = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nationfield = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sexfield = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phone_no = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        balance2field = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        withdrawfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        withdrawpin = new javax.swing.JPasswordField();
        withdrawbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        balance3field = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Taccount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Tamount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Treason = new javax.swing.JTextField();
        transferbtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Tpin = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        history_table = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(706, 430));
        setMinimumSize(new java.awt.Dimension(706, 430));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("WELCOME TO ADWA BANK");

        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        notificationbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notificationbtn.setText("Message");
        notificationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(logoutbtn)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addComponent(logoutbtn)
                .addComponent(notificationbtn))
        );

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(706, 430));
        jTabbedPane1.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Account Name :");

        namefield.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        namefield.setText("Abebe Alemu");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Account no:");

        accountfield.setBackground(new java.awt.Color(204, 204, 204));
        accountfield.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        accountfield.setText("100010101010");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Balance:");

        balancefeild.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        balancefeild.setText("1000 ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Birth date :");

        datefield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datefield.setText("19/23/23");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Nationality:");

        nationfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nationfield.setText("ETHIOPIAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Sex :");

        sexfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sexfield.setText("male");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ETB");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Phone Number :");

        phone_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phone_no.setText("2517282828282");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(balancefeild)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(accountfield, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nationfield, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sexfield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(217, 217, 217)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(balancefeild, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namefield)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountfield))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nationfield)
                    .addComponent(datefield)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sexfield)
                    .addComponent(jLabel11)
                    .addComponent(phone_no))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel2);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Account Balance:");

        balance2field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balance2field.setText("100");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Enter Amount :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("PIN :");

        withdrawbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        withdrawbtn.setText("Conform");
        withdrawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ETB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balance2field, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(withdrawfield))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGap(255, 255, 255)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(withdrawpin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGap(268, 268, 268)
                                    .addComponent(withdrawbtn)))
                            .addGap(25, 25, 25))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(balance2field)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(withdrawpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(withdrawbtn)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Withdraw", jPanel5);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Account Balance :");

        balance3field.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balance3field.setText("100");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Transfer To :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Amount :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Reason :");

        transferbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transferbtn.setText("Conform");
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("PIN :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ETB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Taccount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Tamount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Treason, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tpin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balance3field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferbtn)
                .addGap(265, 265, 265))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance3field)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Taccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Treason, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Tamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(Tpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(transferbtn)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transfer", jPanel4);

        history_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TYPE", "AMOUNT"
            }
        ));
        history_table.setSurrendersFocusOnKeystroke(true);
        history_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                history_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(history_table);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("History", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage li = new LoginPage();
        li.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:

        String taccount = Taccount.getText();
        String tamount = Tamount.getText();
        String treason = Treason.getText();
        String tpin = new String(Tpin.getPassword());

        if (!taccount.isEmpty() && !tamount.isEmpty() && !treason.isEmpty() && !tpin.isEmpty()) {
            if (Integer.parseInt(tamount) >= Integer.parseInt(balance3field.getText())) {
                JOptionPane.showMessageDialog(this, "Insifition balance to transfer");
            }
            if (!tpin.equals(passw)) {
                JOptionPane.showMessageDialog(this, "Wrong pin");
            } else {
                try {

                    int total = Integer.parseInt(balance3field.getText()) - Integer.parseInt(tamount);
                    String new_total = Integer.toString(total);

                    Class.forName(JDBC_DRIVER);
                    String url = CONNECTION_URL;
                    String username = DB_USERNAME;
                    String password = DB_PASSWORD;

                    Connection con = DriverManager.getConnection(url, username, password);

                    PreparedStatement statement = con.prepareStatement("UPDATE user SET balance = ? WHERE account = ?");
                    statement.setInt(1, total);
                    statement.setString(2, accountfield.getText());

                    PreparedStatement ps = con.prepareStatement("insert into message(to_acc,from_acc,amount,reason)values(?,?,?,?)");
                    ps.setString(1, taccount);
                    ps.setString(2, accountfield.getText());
                    ps.setString(3, tamount);
                    ps.setString(4, treason);
                    ps.executeUpdate();

                    PreparedStatement ps1 = con.prepareStatement("insert into transaction(account_no,to_acc,from_acc,amount,reason,transaction_type)values(?,?,?,?,?,?)");

                    ps1.setString(1, taccount);
                    ps1.setString(2, taccount);
                    ps1.setString(3, accountfield.getText());
                    ps1.setString(4, tamount);
                    ps1.setString(5, treason);
                    ps1.setString(6, "Deposite");
                    ps1.executeUpdate();

                    PreparedStatement ps2 = con.prepareStatement("insert into transaction(account_no,to_acc,from_acc,amount,reason,transaction_type)values(?,?,?,?,?,?)");

                    ps2.setString(1, accountfield.getText());
                    ps2.setString(2, taccount);
                    ps2.setString(3, accountfield.getText());
                    ps2.setString(4, tamount);
                    ps2.setString(5, treason);
                    ps2.setString(6, "Transfer");
                    ps2.executeUpdate();

                    PreparedStatement statement_1 = con.prepareStatement("SELECT * FROM user WHERE account = ?");
                    statement_1.setString(1, taccount);
                    ResultSet result = statement_1.executeQuery();
                    if (result.next()) {
                        int Tbal = 0;
                        int tbal = result.getInt("balance");
                        Tbal = tbal;

                        int u_total = Tbal + Integer.parseInt(tamount);
                        PreparedStatement statement_2 = con.prepareStatement("UPDATE user SET balance = ? WHERE account = ?");
                        statement_2.setInt(1, u_total);
                        statement_2.setString(2, taccount);
                        statement_2.executeUpdate();
                        statement.executeUpdate();

                        JOptionPane.showMessageDialog(this, "The transfer has been done successfully!");

                        balancefeild.setText(new_total);
                        balance2field.setText(new_total);
                        balance3field.setText(new_total);

                        transaction_table(accountfield.getText());

                        Taccount.setText("");
                        Tamount.setText("");
                        Treason.setText("");
                        Tpin.setText("");

                    } else {
                        JOptionPane.showMessageDialog(this, "wrong account number");
                    }
                    //int tbalance = Integer.toString(tbal);

                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill The Form");
        }
    }//GEN-LAST:event_transferbtnActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        // TODO add your handling code here:

        if (withdrawpin.getPassword().length == 0 || withdrawfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill The Form");
        } else {
            int withdraw = Integer.parseInt(withdrawfield.getText());
            String pin = new String(withdrawpin.getPassword());
            int balance = Integer.parseInt(balance2field.getText());

            if (withdraw >= balance) {
                JOptionPane.showMessageDialog(this, "INSUFFICIENT BALANCE", pin, HEIGHT);
            } else {
                if (!pin.equals(passw)) {
                    JOptionPane.showMessageDialog(this, "INCORRECT PIN");
                } else {
                    int sum = balance - withdraw;
                    String new_balance = Integer.toString(sum);

                    try {
                        Class.forName(JDBC_DRIVER);
                        String url = CONNECTION_URL;
                        String username = DB_USERNAME;
                        String password = DB_PASSWORD;

                        Connection con = DriverManager.getConnection(url, username, password);

                        PreparedStatement statement = con.prepareStatement("UPDATE user SET balance = ? WHERE account = ?");
                        statement.setInt(1, sum);
                        statement.setString(2, accountfield.getText());
                        statement.executeUpdate();
                        Random rnd = new Random();
                        int n = 100000 + rnd.nextInt(900000);
                        JOptionPane.showMessageDialog(this, "your withdraw code is " + Integer.toString(n));

                        PreparedStatement ps = con.prepareStatement("insert into transaction(account_no,to_acc,from_acc,amount,reason,transaction_type)values(?,?,?,?,?,?)");

                        ps.setString(1, accountfield.getText());
                        ps.setString(2, "");
                        ps.setString(3, "");
                        ps.setString(4, Integer.toString(withdraw));
                        ps.setString(5, "");
                        ps.setString(6, "Withdraw");
                        ps.executeUpdate();

                        transaction_table(accountfield.getText());
                        withdrawfield.setText("");
                        withdrawpin.setText("");
                        balancefeild.setText(new_balance);
                        balance2field.setText(new_balance);
                        balance3field.setText(new_balance);

                    } catch (ClassNotFoundException | SQLException ex) {
                        Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }


    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void notificationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationbtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);
            Statement stat = con.createStatement();
            PreparedStatement statement_1 = con.prepareStatement("SELECT * FROM message WHERE to_acc = ?");
            statement_1.setString(1, accountfield.getText());
            ResultSet result_1 = statement_1.executeQuery();
            if (result_1.next()) {
                String from_acc = result_1.getString("from_acc");
                String amount = result_1.getString("amount");
                String reason = result_1.getString("reason");
                int id = result_1.getInt("id");

                JOptionPane.showMessageDialog(this, "You Have Received " + amount + "\nFrom : " + from_acc + "\nReason : " + reason);

                PreparedStatement del_message = con.prepareStatement("DELETE FROM message WHERE id = ?");
                del_message.setInt(1, id);
                del_message.executeUpdate();
            } else {
                JOptionPane.showMessageDialog(this, "You Have No Message");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_notificationbtnActionPerformed

    private void history_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_history_tableMouseClicked
        // TODO add your handling code here:
        String toacc, fromacc, t_amount, t_reason, ttype;
        
        try {
            Class.forName(JDBC_DRIVER);
            String url = CONNECTION_URL;
            String username = DB_USERNAME;
            String password = DB_PASSWORD;

            Connection con = DriverManager.getConnection(url, username, password);

            //Statement stat = con.createStatement();
            DefaultTableModel df = (DefaultTableModel) history_table.getModel();
            int selectedrow = history_table.getSelectedRow();
            int index = Integer.parseInt(df.getValueAt(selectedrow, 0).toString());
            
            PreparedStatement statement = con.prepareStatement("SELECT * FROM transaction WHERE id = ?");
            statement.setInt(1, index);
            ResultSet result_2 = statement.executeQuery();
            while (result_2.next()) {
                toacc = result_2.getString("to_acc");
                fromacc = result_2.getString("from_acc");
                t_amount = result_2.getString("amount");
                t_reason = result_2.getString("reason");
                ttype = result_2.getString("transaction_type");
                if (ttype.equals("Withdraw")) {
                    JOptionPane.showMessageDialog(this, ""
                            + "Amount = " + t_amount + "\n"
                            + ttype);
                } else if (ttype.equals("Deposite")) {
                    JOptionPane.showMessageDialog(this, ""
                            + "Amount = " + t_amount + "\n"
                            + "From = " + fromacc + "\n"
                            + "Reason = " + t_reason + "\n"
                            + ttype);
                } else if (ttype.equals("Transfer")) {
                    JOptionPane.showMessageDialog(this, ""
                            + "Amount = " + t_amount + "\n"
                            + "To = " + toacc + "\n"
                            + "Reason = " + t_reason + "\n"
                            + ttype);
                }

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AccountantPage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_history_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Taccount;
    private javax.swing.JTextField Tamount;
    private javax.swing.JPasswordField Tpin;
    private javax.swing.JTextField Treason;
    private javax.swing.JLabel accountfield;
    private javax.swing.JLabel balance2field;
    private javax.swing.JLabel balance3field;
    private javax.swing.JLabel balancefeild;
    private javax.swing.JLabel datefield;
    private javax.swing.JTable history_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel namefield;
    private javax.swing.JLabel nationfield;
    private javax.swing.JButton notificationbtn;
    private javax.swing.JLabel phone_no;
    private javax.swing.JLabel sexfield;
    private javax.swing.JButton transferbtn;
    private javax.swing.JButton withdrawbtn;
    private javax.swing.JTextField withdrawfield;
    private javax.swing.JPasswordField withdrawpin;
    // End of variables declaration//GEN-END:variables
}
